version: "3.8"
services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wg-ui
    environment:
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WG_CONF_DIR=/etc/wireguard
    volumes:
      - /etc/wireguard:/etc/wireguard
      - /etc/wireguard/clients:/etc/wireguard/clients
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    network_mode: host